name: Assign and Check Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  BS7000_check_PR:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Assign PR to creator
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const assignee = context.payload.pull_request.user.login;
          await github.rest.issues.addAssignees({
            owner,
            repo,
            issue_number: number,
            assignees: [assignee],
          });
          console.log(`✅ Assigned PR #${number} to ${assignee}`);
      
    # Check if the /ipk folder exists
    - name: Check for ipk folder
      id: check_ipk
      run: |
        if [ -d "ipk" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    # Only runs if the previous step found IPK folder
    - name: Run local script
      if: steps.check_ipk.outputs.exists == 'true'
      run: |
        echo "${{ github.event.pull_request.number }}" > PR_NUMBER.txt
        chmod +x ~/tools/github_actions/BS7000_check_PR.sh
        ~/tools/github_actions/BS7000_check_PR.sh