name: PR Opened
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  PR_opened:
    runs-on: self-hosted

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Assign PR to creator
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const assignee = context.payload.pull_request.user.login;
          await github.rest.issues.addAssignees({
            owner,
            repo,
            issue_number: number,
            assignees: [assignee],
          });
          console.log(`✅ Assigned PR #${number} to ${assignee}`);
      
    - name: Run local script
      run: |
        echo "${{ github.event.pull_request.number }}" > PR_NUMBER.txt
        chmod +x ~/tools/github_actions/BS7000_check_PR.sh
        ~/tools/github_actions/BS7000_check_PR.sh
